apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudscrew-deployment
  labels:
    app: cloudscrew
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudscrew
  template:
    metadata:
      labels:
        app: cloudscrew
    spec:
      containers:
      - name: cloudscrew
        image: hub-registry.me-central-1.cr.aliyuncs.com/hub/hcth:cloudScrew
        ports:
        - containerPort: 80