apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudscrew-deployment
  labels:
    app: cloudscrew
spec:
  replicas: 4
  selector:
    matchLabels:
      app: cloudscrew
  template:
    metadata:
      labels:
        app: cloudscrew
    spec:
      containers:
      - name: cloudscrew
        image: <URL>
        ports:
        - containerPort: 80